# Generated by Django 5.1.5 on 2025-02-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_url', models.CharField(max_length=255)),
                ('color', models.CharField(default='#ffffff', max_length=20)),
                ('position_x', models.IntegerField(default=100)),
                ('position_y', models.IntegerField(default=100)),
            ],
        ),
    ]
