# Generated by Django 5.1.5 on 2025-02-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='url',
            field=models.URLField(default='#'),
        ),
    ]
