# Generated by Django 5.1.5 on 2025-02-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_toolbox_position_x_remove_toolbox_position_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbox',
            name='x',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='toolbox',
            name='y',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='toolbox',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='toolbox',
            name='width',
            field=models.IntegerField(default=150),
        ),
    ]
